[package]
name = "tutorial_rust"
version = "0.1.0"
authors = ["ethan <ethan@fuzzbuzz.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]

[dependencies]
